spring.application.name=cklt-web

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/cklt_web_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daigianguoi@gmail.com
spring.mail.password=oaqnowqwftigtnrs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary
cloudinary.cloud-name=ccgkesp4
cloudinary.api-key=971596393999274
cloudinary.api-secret=YwTpCA8ium1FD7A8nVwfsxP45Ig

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB